a:
	g++ -std=c++14 a.cpp
	./a.out < test_a

b:
	g++ -std=c++14 b.cpp
	./a.out < test_b

c:
	g++ -std=c++14 c.cpp
	./a.out < test_c

d:
	g++ -std=c++14 d.cpp
	./a.out < test_d

e:
	g++ -std=c++14 e.cpp
	./a.out < test_e

f:
	g++ -std=c++14 f.cpp
	./a.out < test_f
