a:
	g++ -std=c++17 -Wall a.cpp
	./a.out < test_a

b:
	g++ -std=c++17 -Wall b.cpp
	./a.out < test_b

c:
	g++ -std=c++17 -Wall c.cpp
	./a.out < test_c

d:
	g++ -std=c++17 -Wall d.cpp
	./a.out < test_d

e:
	g++ -std=c++17 -Wall e.cpp
	./a.out < test_e

f:
	g++ -std=c++17 -Wall f.cpp
	./a.out < test_f
